### ISSUE TITLE
[Bug] Spring Boot 3.4.0 실행 시 Hibernate DB 메타데이터 로드 실패 로그 발생

### ISSUE THREAD

**Issue by kmindev** [kmindev/my-board-backend#19]
## ❗️어떤 버그인가요?

> Spring Boot 3.4.0 버전과 Spring Data JPA를 사용하여 애플리케이션을 개발 중이다.
> 기존과 동일한 설정과 환경에서 작업하고 있음에도 Hibernate 초기화 단계에서 평소 보지 못했던 INFO 레벨의 로그가 출력된다. 
> 애플리케이션의 정상적인 동작에는 영향을 미치지 않지만, Hibernate가 데이터베이스 메타데이터를 읽지 못한 것으로 보이는 로그가 찜찜하다..

## 📇어떤 상황에서 발생한 버그인가요?
> Spring Boot 3.4.0 버전에서 H2 Database를 사용 중이다. Spring Data JPA와 설정은 다음과 같다.

**application.yml**
```
spring:
  datasource:
    url: jdbc:h2:mem:my-board
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql.init.mode: always
  h2.console.enabled: true
```

> Boot 실행 시 애플리케이션은 정상적으로 동작하지만, Hibernate가 Database 메타정보를 제대로 읽지 못한다는 INFO 로그가 출력된다.
![Image](https://github.com/user-attachments/assets/8bf9be35-50e0-46bb-8c47-b741646d8ac9)

## 🎯예상 결과
> Spring Boot 이전 버전을 사용할 때는 출력되지 않는 로그이다. 해당 로그가 어떤 문제로부터 출력되는 로그인지 확인해보자.
